web/router.ex
defmodule Money.Router do
  use Money.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Money.Auth, repo: Money.Repo
    plug :preload_user_data, repo: Money.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash # FIXME temp, not needed
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Money.Auth, repo: Money.Repo
    plug :preload_user_data, repo: Money.Repo
  end

  scope "/", Money do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/", Money do
    pipe_through [:browser, :authenticate_user]

    resources "/accounts", AccountController
    get "/budget", BudgetController, :index
    get "/budget/:year/:month", BudgetController, :show

    get "/accounts/:account_id/import", ImportController, :new
    post "/accounts/:account_id/import", ImportController, :parse
  end

  # TODO post transaction and get html formated return.
  # Use another controller or the same? It's not possible to use the same?
  scope "/api/v1", Money do
    pipe_through [:api, :authenticate_user]

    resources "/transactions", TransactionController, only: [:create, :update, :delete]
    delete "/transactions", TransactionController, :delete_transactions
    delete "/accounts/:id/transactions", AccountController, :delete_transactions

    resources "/categories", CategoryController, only: [:create, :update]
    delete "/categories", CategoryController, :delete_categories

    resources "/category_groups", CategoryGroupController, only: [:create, :update]

    resources "/budgeted_categories", BudgetedCategoryController, only: [:create]
    post "/budgeted_categories/:year/:month", BudgetedCategoryController, :create
    patch "/budgeted_categories/:year/:month", BudgetedCategoryController, :save
    put "/budgeted_categories/:year/:month", BudgetedCategoryController, :save
  end
end

web/views/layout_view.ex
defmodule Money.LayoutView do
  use Money.Web, :view

  # view specific js module name generation
  # https://blog.diacode.com/page-specific-javascript-in-phoenix-framework-pt-1
  def js_view_name(conn, view_template) do
    [view_name(conn), template_name(view_template)]
    |> Enum.reverse
    |> List.insert_at(0, "view")
    |> Enum.map(&String.capitalize/1)
    |> Enum.reverse
    |> Enum.join("")
  end

  defp view_name(conn) do
    conn
    |> view_module
    |> Phoenix.Naming.resource_name
    |> String.replace("_view", "")
  end

  defp template_name(template) when is_binary(template) do
    template
    |> String.split(".")
    |> Enum.at(0)
  end
end

web/templates/layout/alerts.html.eex
<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>MoneyTracker9000</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body data-js-view-name="<%= js_view_name(@conn, @view_template) %>">
    <%# Use sidebar layout if we're logged in, otherwise main fills whole screen. %>
    <%= if @current_user do %>
      <nav class="sidebar">
        <ul>
          <li><%= active_link_starts_with @conn, "/budget/", "Budget", to: budget_path(@conn, :index) %></li>
          <li>
            <%= active_link @conn, "All Accounts", to: account_path(@conn, :index) %>
            <%= link "new", to: account_path(@conn, :new), class: "extra" %>
          </li>
          <%= for account <- @current_user.accounts do %>
            <li class="account">
              <%= active_link @conn, account.title, to: account_path(@conn, :show, account.id) %> 
              <%= link "edit", to: account_path(@conn, :edit, account), class: "extra" %>
            </li>
          <% end %>
        </ul>
      </nav>
    <% end %>

    <header class="header">
      <span class="logo">
        MoneyTracker9000
      </span>

      <div class="right">
        <ol>
          <%= if @current_user do %>
            <li><%= @current_user.username %></li>
            <li><%= link "Settings", to: "#" %></li>
            <li>
              <%= link "Log out", to: session_path(@conn, :delete, @current_user),
                                  method: "delete" %>
            </li>
          <% else %>
            <li><%= link "Register", to: user_path(@conn, :new) %></li>
            <li><%= link "Log in", to: session_path(@conn, :new) %></li>
          <% end %>
        </ol>
      </div>
    </header>

    <%= if @current_user do %>
      <main role="main" class="right-main">
        <%= render "alerts.html", assigns %>
        <%= render @view_module, @view_template, assigns %>
      </main>
    <% else %>
      <div id="main-wrapper">
        <main role="main" class="centered-main">
          <%= render "alerts.html", assigns %>
          <%= render @view_module, @view_template, assigns %>
        </main>
      </div>
    <% end %>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>