web/router.ex
defmodule Money.Router do
  use Money.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Money.Auth, repo: Money.Repo
    plug :preload_user_data, repo: Money.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash # FIXME temp, not needed
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Money.Auth, repo: Money.Repo
    plug :preload_user_data, repo: Money.Repo
  end

  scope "/", Money do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/", Money do
    pipe_through [:browser, :authenticate_user]

    resources "/accounts", AccountController
    get "/budget", BudgetController, :index
    get "/budget/:year/:month", BudgetController, :show

    get "/accounts/:account_id/import", ImportController, :new
    post "/accounts/:account_id/import", ImportController, :parse
  end

  # TODO post transaction and get html formated return.
  # Use another controller or the same? It's not possible to use the same?
  scope "/api/v1", Money do
    pipe_through [:api, :authenticate_user]

    resources "/transactions", TransactionController, only: [:create, :update, :delete]
    delete "/transactions", TransactionController, :delete_transactions
    delete "/accounts/:id/transactions", AccountController, :delete_transactions

    resources "/categories", CategoryController, only: [:create, :update]
    delete "/categories", CategoryController, :delete_categories

    resources "/category_groups", CategoryGroupController, only: [:create, :update]

    resources "/budgeted_categories", BudgetedCategoryController, only: [:create]
    post "/budgeted_categories/:year/:month", BudgetedCategoryController, :create
    patch "/budgeted_categories/:year/:month", BudgetedCategoryController, :save
    put "/budgeted_categories/:year/:month", BudgetedCategoryController, :save
  end
end

web/controllers/budget_controller.ex
defmodule Money.BudgetController do
  use Money.Web, :controller
  alias Money.Router.Helpers
  alias Money.BudgetedCategory
  alias Money.BudgetedCategoryGroup

  def action(conn, _) do
    apply(__MODULE__, action_name(conn),
     [conn, conn.params, conn.assigns.current_user])
  end

  def index(conn, _params, _user) do
    # TODO redirect to last viewed month
    {{year, month, _}, _} = :calendar.local_time()

    conn |> redirect(to: Helpers.budget_path(conn, :show, year, month))
  end

  def show(conn, %{"year" => year, "month" => month}, user) do
    year = String.to_integer(year)
    month = String.to_integer(month)

    budget = monthly_budget(user, year, month)
    render(conn, "show.html", year: year, month: month, budget: budget)
  end
end

web/views/budget_view.ex
defmodule Money.BudgetView do
  use Money.Web, :view
end

web/templates/budget/show.html.eex
<div id="main-budget">

  <div id="budget" class="grid">
    <div id="budget-header">
      <%# Display prettier %>
      <%= "year: #{@year} month: #{@month}" %>
      <nav>
        <ol>
          <li><%= link "Add category group", to: "#", class: "add-category-group" %></li>
          <!---
          <li><%= link "Undo", to: "#" %></li>
          <li><%= link "Redo", to: "#" %></li>
          -->
          <li>
            <%= form_for @conn, category_path(@conn, :delete_categories), [as: :data, id: "delete-selected"], fn _ -> %>
              <%= submit "Delete" %>
            <% end %>
          </li>
        </ol>
      </nav>
    </div>

    <%= form_for @conn, category_group_path(@conn, :create), [as: :category_group, id: "create-category-group", class: "hidden"], fn f -> %>
      <%= text_input f, :name, placeholder: "Category Group" %>
      <%= submit "Add" %>
    <% end %>

    <div class="grid-header">
      <div class="grid-header-cell grid-budget-cb"><input type="checkbox"></div>
      <div class="grid-header-cell grid-budget-category">Category</div>
      <div class="grid-header-cell grid-budget-budgeted">Budgeted</div>
      <div class="grid-header-cell grid-budget-activity">Activity</div>
      <div class="grid-header-cell grid-budget-balance">Balance</div>
    </div>

    <div class="grid-body">
      <%= for group <- @budget do %>
        <%= render Money.BudgetedCategoryGroupView, "row.html",
                                                    group: group,
                                                    conn: @conn %>
        <%= for c <- group.budgeted_categories do %>
          <%= render Money.BudgetedCategoryView, "row.html",
                                                 c: c,
                                                 conn: @conn %>
        <% end %>
      <% end %>
    </div>

  </div>

  <div id="budget-info">
    <div class="category">
      <span class="name">Category Name</span>
    </div>

    <div class="money-info">
      <!---
      <span class="money-row">
        Cash Left Over From June
        <span class="amount">0.00</span>
      </span>
      -->

      <span class="money-row budgeted-this-month">
        Budgeted This Month
        <span class="amount">+3,000.00</span>
      </span>

      <span class="money-row spending">
        Spending
        <span class="amount">0.00</span>
      </span>
    </div>

    <div class="available-money">
      Available
      <span class="amount">3000.00</span>
    </div>

    <!---
    <div class="upcoming">
      <span class="money-row">
        1 Upcoming Transaction
        <span class="amount">0.00</span>
      </span>

      <span class="money-row">
        Available After Upcoming
        <span class="amount">3000.00</span>
      </span>
    </div>
    -->

    <div class="quick-budget">
      <div class="title">
        Quick budget
      </div>
      <ul>
        <li><a href="#">Budgeted Last Month: 0</a></li>
        <li><a href="#">Spent Last Month: 0</a></li>
        <li><a href="#">Average Budgeted: 0</a></li>
        <li><a href="#">Average Spent: 0</a></li>
      </ul>
    </div>
  </div>

  <div class="hidden">
    <%= form_tag(budgeted_category_path(@conn, :create, @year, @month), id: "new-category") %></form>
    <%= form_tag(budgeted_category_path(@conn, :save, @year, @month), id: "update-category") %></form>
  </div>
</div>